---
title: "Analyse de données avancées"
author: "Bertrand GAKIZA"
format: html
editor: visual
---

## CAH directe avec distance de Gower

```{r}

# Importation
data <- read.csv("C:/Users/HP/Desktop/skuuul/M2/Analyse de donnees avance/Projet/bank.csv", sep=";", stringsAsFactors=TRUE)
names(data)
```

## Descriptive des données

```{r}
summary(data)
```

```{r}
library(FactoMineR)
library(cluster)
library(factoextra)
```

## CAH sur la distance de Gower

```{r}
# Calcul de la distance de Gower entre les clients
d.gower <- daisy(data, metric = "gower")

# CAH sur la matrice de distance avec méthode de Ward
cah.gow <- hclust(d.gower, method = "ward.D2")
plot(cah.gow, cex=0.8)

```

```{r}
# Choix d'une partition en 4 classes
k <- 4
# Variable de partition
data$parti <- as.factor(cutree(cah.gow, k))
```

```{r}
# Memorisation Partition avec Gower
parti.gow <- data$parti
```

## CAH sur les facteurs de l'AFDM

```{r}
afdm.data <- FAMD(data, ncp = Inf)
afdm.data$eig
fviz_eig(afdm.data, addlabels = T)
# On prend 2 dimensions
afdm.data <- FAMD(data, ncp = 2)
```

```{r}
# Partition Interactive
cah.afdm <- HCPC(afdm.data, nb.clust = 0, proba = 0.30)

```

```{r}
# Partition Optimale : on retient 2 classes (la partition optimale)
cah.afdm <- HCPC(afdm.data, nb.clust = 2, proba = 0.30)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

The `echo: false` option disables the printing of code (only output is displayed).
